#include "my_iocon.h"
#include "my_i2c.h"

#define LED1_PIN_MUX 		IOCON_PIO0_7
#define LED2_PIN_MUX 		IOCON_PIO1_0
#define LED3_PIN_MUX 		IOCON_PIO1_4
#define LED4_PIN_MUX 		IOCON_PIO1_5

#define SW1_PIN_MUX 			IOCON_PIO1_8
#define SW2_PIN_MUX 			IOCON_PIO1_9
#define SW3_PIN_MUX 			IOCON_PIO0_1
#define SW4_PIN_MUX 			IOCON_PIO0_3

#define UART_TXD_PIN_MUX 	IOCON_PIO1_7
#define UART_RXD_PIN_MUX 	IOCON_PIO1_6

#define I2C_SCL_PIN_MUX 		IOCON_PIO0_4
#define I2C_SDA_PIN_MUX 		IOCON_PIO0_5

#define SSP_MISO_PIN_MUX 	IOCON_PIO0_8
#define SSP_MOSI_PIN_MUX 	IOCON_PIO0_9
#define SSP_SCK_PIN_MUX 		IOCON_PIO0_6
#define SSP_CS_PIN_MUX 		IOCON_PIO0_2

#define ADC0_PIN_MUX 		IOCON_PIO0_11

#define PWM0_PIN_MUX 		IOCON_PIO1_1
#define PWM1_PIN_MUX 		IOCON_PIO1_2

#define CLKOUT_PIN_MUX		IOCON_PIO0_1
#define CAP0_PIN_MUX			IOCON_PIO1_5

void IOCON_Config_Request(void)
{
	// LED
	Chip_IOCON_PinMuxSet(LPC_IOCON, LED1_PIN_MUX, FUNC0);
	Chip_IOCON_PinMuxSet(LPC_IOCON, LED2_PIN_MUX, FUNC0);
	Chip_IOCON_PinMuxSet(LPC_IOCON, LED3_PIN_MUX, FUNC0);
	Chip_IOCON_PinMuxSet(LPC_IOCON, LED4_PIN_MUX, FUNC0);
	// SW
	Chip_IOCON_PinMuxSet(LPC_IOCON, SW1_PIN_MUX,	(IOCON_FUNC0 | IOCON_MODE_PULLUP | IOCON_DIGMODE_EN));
	Chip_IOCON_PinMuxSet(LPC_IOCON, SW2_PIN_MUX,	(IOCON_FUNC0 | IOCON_MODE_PULLUP | IOCON_DIGMODE_EN));
	Chip_IOCON_PinMuxSet(LPC_IOCON, SW3_PIN_MUX,	(IOCON_FUNC0 | IOCON_MODE_PULLUP | IOCON_DIGMODE_EN));
	Chip_IOCON_PinMuxSet(LPC_IOCON, SW4_PIN_MUX,	(IOCON_FUNC0 | IOCON_MODE_PULLUP | IOCON_DIGMODE_EN));
	// PWM
	Chip_IOCON_PinMuxSet(LPC_IOCON, PWM0_PIN_MUX, (IOCON_FUNC3 | IOCON_INV_EN | IOCON_DIGMODE_EN));
	// UART
	Chip_IOCON_PinMuxSet(LPC_IOCON, UART_RXD_PIN_MUX, (IOCON_FUNC1 | IOCON_MODE_INACT));
	Chip_IOCON_PinMuxSet(LPC_IOCON, UART_TXD_PIN_MUX, (IOCON_FUNC1 | IOCON_MODE_INACT));
	// ADC
	Chip_IOCON_PinMuxSet(LPC_IOCON, ADC0_PIN_MUX, FUNC2);
	// I2C
	Chip_IOCON_PinMuxSet(LPC_IOCON, I2C_SCL_PIN_MUX, IOCON_FUNC1 | I2C_FASTPLUS_BIT);
	Chip_IOCON_PinMuxSet(LPC_IOCON, I2C_SDA_PIN_MUX, IOCON_FUNC1 | I2C_FASTPLUS_BIT);
	// SSP
	Chip_IOCON_PinLocSel(LPC_IOCON, IOCON_SCKLOC_PIO0_6);
	Chip_IOCON_PinMuxSet(LPC_IOCON, SSP_SCK_PIN_MUX, 2);
	Chip_IOCON_PinMuxSet(LPC_IOCON, SSP_MOSI_PIN_MUX, (IOCON_FUNC1 | IOCON_MODE_PULLUP));
	Chip_IOCON_PinMuxSet(LPC_IOCON, SSP_MISO_PIN_MUX, (IOCON_FUNC1 | IOCON_MODE_PULLUP));
	// CLKOUT
//	Chip_IOCON_PinMuxSet(LPC_IOCON, CLKOUT_PIN_MUX, (IOCON_FUNC1 | IOCON_MODE_INACT));
   // CAPTURE
// Chip_IOCON_PinMuxSet(LPC_IOCON, CAP0_PIN_MUX, IOCON_FUNC2 | IOCON_MODE_PULLUP | IOCON_DIGMODE_EN);

}
